export interface Restaurant{
    name: String,
    key: String,
    address: String,
    municipality: String,
    workHoursWorkdays: String,
    workHoursSaturday: String,
    workHoursSunday: String,
    cuisine: String,
    dressCode: String,
    paymentOptions: Boolean,
    additional: String,
    website: String,
    contactPhone: String,
    category: Number,
    capacity: Number,
    description: String,
    mainPicture: String,
    coverPicture: String,
    pictures: Array<String>,
    latitude: Number,
    longitude: Number,
    sumGrades: Number,
    totalGrades: Number,
    distanceNumber: Number,
    distanceString: String,
    durationString: String
}